[build]
builder = "nixpacks"
buildCommand = "create_static"

[deploy]
startCommand = "gunicorn catsite.wsgi --log-file -"

[services]
  [services.web]
  command = "python3 manage.py makemigrations --no-input && python3 manage.py migrate --no-input"