#!/bin/bash
# Navigate to the cat-app subdirectory and run the following commands:
cd cat-app
npm run build
# return to main folder
cd - 
#pip install -r requirements.txt
python3 manage.py makemigrations --no-input 
python3 manage.py migrate --no-input
# run server
gunicorn catsite.wsgi --log-file -
