# Generated by Django 4.0 on 2021-12-27 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catlogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='creation_date',
            new_name='feed_time',
        ),
    ]
