# Generated by Django 4.0 on 2022-01-05 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catlogs', '0004_alter_cat_image_alter_log_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='amount',
            field=models.CharField(blank=True, choices=[('small', 'small'), ('medium', 'medium'), ('large', 'large')], default='small', max_length=60, null=True),
        ),
    ]
